### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by hzlsdxx** [MrtnMndt/meta-learning-CODEBRIM#5]
Hi, the download link for the Bridge Damage Dataset is not available.

**Comment by MrtnMndt** [comment]
Hi, I am not sure what you mean. 
The link that is in the Readme, pointing to Zenodo, works perfectly fine and the download there seems to start properly too: https://doi.org/10.5281/zenodo.2620293 
Can you clarify what specifically does not seem to work with the "download link is not available?"

**Comment by hzlsdxx** [comment]
Thank you, I have solved this problem.
