### ISSUE TITLE
the problem of label

### ISSUE THREAD

**Issue by ailiwei17** [MrtnMndt/meta-learning-CODEBRIM#6]
hello, I download a part of dataset.The zip file "CODEBRIM_crop_dataset" only includes images, but no labels.How can I download data which has been labeled?

**Comment by ailiwei17** [comment]
I think this problem has been solved

**Comment by RUGoodMalaysia** [comment]
> 我认为这个问题已经解决了

How do you solve this problem? I have downloaded Original Dataset, but I dont know how to use

**Comment by MrtnMndt** [comment]
@RUGoodMalaysia  There are multiple versions of the dataset on Zenodo for convenience (depending on what kind of training and evaluation you want to run). 
For instance, you can decide if you want to download the dataset in a format relevant for classification, or the original images if you care about e.g. locations.  

Please check the readme and download the correct version.
